version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: devops-backend
    ports:
      - "8000:8000"
    networks:
      - devops-net

  frontend:
    build:
      context: ./frontend
    container_name: devops-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - devops-net

networks:
  devops-net:
    driver: bridge
