name: Build and Push to ECR

on:
  push:
    branches: [develop]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: 533267107704.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
  ECR_REPO_FRONTEND: ${{ secrets.ECR_REPO_FRONTEND }}
  ECR_REPO_BACKEND: ${{ secrets.ECR_REPO_BACKEND }}

jobs:
  push-to-ecr:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Download ALB URL artifact
        run: |
          curl -L -o alb.txt https://github.com/MustafaMiyaji/DevOps-Assignment/releases/download/temp-release/alb.txt

      - name: Read ALB URL
        id: alb
        run: |
          echo "ALB_URL=$(cat alb.txt)" >> $GITHUB_ENV

      - name: Build frontend image
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_API_URL=http://${{ env.ALB_URL }}/api \
            -t $ECR_REGISTRY/$ECR_REPO_FRONTEND:latest \
            ./frontend

      - name: Push frontend image
        run: |
          docker push $ECR_REGISTRY/$ECR_REPO_FRONTEND:latest

      - name: Force ECS redeploy frontend
        run: |
          aws ecs update-service \
            --cluster devops-assignment-cluster \
            --service devops-assignment-frontend-service \
            --force-new-deployment \
            --region $AWS_REGION

      - name: Build backend image
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPO_BACKEND:latest ./backend

      - name: Push backend image
        run: |
          docker push $ECR_REGISTRY/$ECR_REPO_BACKEND:latest

      - name: Force ECS redeploy backend
        run: |
          aws ecs update-service \
            --cluster devops-assignment-cluster \
            --service devops-assignment-backend-service \
            --force-new-deployment \
            --region $AWS_REGION
